version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: geotest-app
    command: > 
      bash -c "bin/docker-bundle.sh 
      && rm -f tmp/pids/server.pid 
      && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - bundle_cache:/bundle
      - .:/geotest
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=geotest
      - POSTGRES_PASSWORD=geotest
    volumes:
      - pgdata:/var/lib/postgresql/data

  spec:
    image: geotest-app
    links:
      - db
    volumes:
      - bundle_cache:/bundle
      - .:/geotest

volumes:
  bundle_cache:
  pgdata:
